# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Public Transportation Commission

email: webrequest@hillsboroughcounty.org

description: Public Transportation Commission (PTC) is an independent Special District that regulates vehicles for-hire as defined in a Special Act

baseurl: "/pub_trans_comm"

url: ""

facebook: "https://www.facebook.com/PublicTransportationCommission?_rdr=p"
twitter: "https://twitter.com/ptchills"

# Build settings
markdown: kramdown

paginate: 2
paginate_path: "/info/:num"

gems:
 - jekyll-coffeescript
 - jekyll-paginate
